German Translation
PlexRipper/PlexRipper pull request #98
Opened 2021-11-23 12:44 UTC by padso4tw

2022-04-25 21:41 UTC, Animizio approved these changes
this translations are good :)

2022-06-24 16:39 UTC, fxsth requested changes
I dont understand the previous review. Actually these are poor translations full of spelling errors.

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +			"sync-server-libraries": "Server Mediatheken Synchronisieren",
"Server-Mediatheken synchronisieren"

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +			"hide": "verstecken"
"Ausblenden"

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +					"text": "Standartpfad für Filme wenn kein individueller Pfad angegeben wurde."
Standard..., not Standart...

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +						"text": "PlexRipper Multithread-Downloads und kann Medien, die heruntergeladen werden sollen, in individuellen teilen herunterladen und wieder zusammen führen. Das führt in der regel zu einer h
"PlexRipper unterstützt Multithread-Downloads und kann Medien, die heruntergeladen werden sollen, in Segmente aufteilen und individuell herunterladen. Das führt in der Regel zu einer höheren Downloadgeschwindigkeit, benötigt jedoch zusätzlich Zeit um die Segmente  wieder zusammenzusetzen.\n\nDas Setzen auf den Wert 1 deaktiviert die Funktion und lädt die Datei am Stück herunter. Die Anzahl der Segmente hat keinen Einfluss auf die Dauer des Zusammensetzens."

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +			"text": "This will delete this Plex account from Plex Ripper! \n\n This will also delete all inaccessible Plex shared servers, Plex libraries and all media that is contained within. Any active dow
Dadurch wird der Plex-Account auf dem Plex Ripper gelöscht!\n\nEbenso werden alle nicht erreichbaren geteilten Plex-Server, Plex-Mediatheken und alle darin enthaltenen Medien gelöscht. Aktive Downloads, die mit diesem Account gestartet oder in die Warteschlange eingereiht wurden, werden abgebrochen und gelöscht. Abgeschlossene Downloads hingegen werden nicht angefasst.

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +				"title": "Sie sind Genial, weil Sie PlexRipper ausprobieren!",
"Sie sind großartig, weil Sie PlexRipper ausprobieren"

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +					"label": "Serien Pfad",
Serienpfad

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +						"label": "Datum kurzformat",
"Datumsformat (kurz)"

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +						"label": "Dazum langformat",
"Datumsformat (lang)"

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +						"label": "Zeit Format",
"Zeitformat"

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +						"label": "Zeige Relative Daten",
"Zeige relative Daten"

2022-06-24 16:39 UTC, fxsth commented on src/WebAPI/ClientApp/src/lang/de_DE.json
> +				"header": "Film Überischt",
It's "Übersicht" not "Überischt"

2022-06-25 11:50 UTC, JasonLandbridge commented
@fxsth, I had merged the orginal German translations to the dev branch, without your changes. Please make a seperate PR for this file: [https://github.com/PlexRipper/PlexRipper/blob/dev/src/WebAPI/ClientApp/src/lang/de-DE.json](https://github.com/PlexRipper/PlexRipper/blob/dev/src/WebAPI/ClientApp/src/lang/de-DE.json) if you can improve it, thanks!

2022-06-25 11:50 UTC, closed without merging